apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders
resources:
  - namespace.yaml
  - postgresql-secret.yaml
  - rabbitmq-secret.yaml
  - configMap.yaml
  - serviceAccount.yaml
  - service.yaml
  - postgresql-service.yaml
  - rabbitmq-service.yaml
  - deployment.yaml
  - postgresql-statefulset.yaml
  - rabbitmq-statefulset.yaml
