apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "catalog-external-secret"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "cluster-secret-store"
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "$CATALOG_SECRET_NAME"
