apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  annotations:
    # This annotation is only required when using IRSA. It will be null when using Pod Identity
    eks.amazonaws.com/role-arn: ${CARTS_IAM_ROLE}