apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: catalog
spec:
  template:
    spec:
      containers:
        - name: catalog
          volumeMounts:
            - name: catalog-secret
              mountPath: "/mnt/catalog-secret"
              readOnly: true
      volumes:
        - name: catalog-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: catalog-spc
