apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-multi
spec:
  initContainers:
  - command:
    - sleep
    - "5"
    image: ubuntu:22.04
    name: ubuntu0
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu:22.04
    name: ubuntu1
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
  - command:
    - sleep
    - infinity
    image: ubuntu:22.04
    name: ubuntu2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
