apiVersion: v1
kind: Pod
metadata:
  name: pod-25-128
spec:
  containers:
  - name: stress-ng
    image: colinianking/stress-ng
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args: ["--cpu", "1", "--cpu-load", "25", "--vm", "1", "--vm-bytes", "128M"]
