apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    # Select EKS optimized AL2023 AMIs with the latest version. This term is mutually
    # exclusive and can't be specified with other terms.
    - alias: al2023@latest
  role: "$KARPENTER_ROLE"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: $EKS_CLUSTER_NAME
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: $EKS_CLUSTER_NAME
  tags:
    app.kubernetes.io/created-by: eks-workshop