apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster1
  server: https://rancher.mydomain.net/k8s/clusters/<cluster-id>
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
