apiVersion: v1
kind: Secret
metadata:
  name: orders-db
data:
  url: "amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJzP2FsbG93UHVibGljS2V5UmV0cmlldmFsPXRydWU="
  username: "b3JkZXJzX3VzZXI="
  password: "ZGVmYXVsdF9wYXNzd29yZA=="
