global:
  scrape_interval: 5s
  external_labels:
    cluster: eu1
    replica: 0
    tenant: team-eu # Not needed, but a good practice if you want to grow this to multi-tenant system some day.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-0-eu1:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['prometheus-0-eu1-sidecar:19090']
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
  - job_name: 'querier'
    static_configs:
      - targets: ['querier:9091']
  - job_name: 'store_gateway'
    static_configs:
      - targets: ['store-gateway:19091']
  - job_name: 'compactor'
    static_configs:
      - targets: ['thanos-compact:19095']

